name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:  # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://srucodingclub1.onrender.com/api/v1/health > /dev/null
          echo "Pinged Render app to keep it alive"
